import {
  ConfigPlugin,
  withAppBuildGradle,
  withProjectBuildGradle,
  withAndroidManifest,
  withDangerousMod,
  AndroidConfig,
} from "expo/config-plugins";
import fs from "fs";
import path from "path";

// Injects the Jetpack Glance loadpoint widget into the prebuilt Android
// project. Android counterpart of the @bacons/apple-targets iOS widget.

const PACKAGE = "io.evcc.android";
const WIDGET_SUBDIR = "widget"; // io.evcc.android.widget
const KOTLIN_SRC = "targets/android-widget/kotlin";
// Translations: shared widget strings come from the committed iOS string
// catalog (generated by `npm run widget:strings`), Android-only config
// Activity strings straight from this app's i18n JSON.
const XCSTRINGS = "targets/widget/Localizable.xcstrings";
const APP_I18N = "i18n";
const ANDROID_ONLY_PREFIX = "widget.androidConfig.";

const GLANCE_VERSION = "1.1.1";

// The Compose compiler gradle plugin is versioned with Kotlin (2.0+) and must
// match the Kotlin version React Native's gradle plugin pins.
function kotlinVersion(projectRoot: string): string {
  const toml = fs.readFileSync(
    path.join(
      projectRoot,
      "node_modules/react-native/gradle/libs.versions.toml",
    ),
    "utf8",
  );
  const m = toml.match(/^kotlin\s*=\s*"([^"]+)"/m);
  if (!m)
    throw new Error(
      "withAndroidWidget: Kotlin version not found in react-native libs.versions.toml",
    );
  return m[1];
}

const withComposeClasspath: ConfigPlugin = (config) =>
  withProjectBuildGradle(config, (config) => {
    if (
      !config.modResults.contents.includes("compose-compiler-gradle-plugin")
    ) {
      const cp = `classpath("org.jetbrains.kotlin:compose-compiler-gradle-plugin:${kotlinVersion(config.modRequest.projectRoot)}")`;
      config.modResults.contents = config.modResults.contents.replace(
        /(classpath\(["']com\.android\.tools\.build:gradle["'][^\n]*\)\n)/,
        (m) => `${m}    ${cp}\n`,
      );
    }
    return config;
  });

const withGlanceGradle: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (config) => {
    let src = config.modResults.contents;

    const apply = `apply plugin: "org.jetbrains.kotlin.plugin.compose"`;
    if (!src.includes(apply)) src = `${apply}\n${src}`;

    if (!src.includes("glance-appwidget")) {
      // Glance brings a compatible Compose runtime transitively, so no BOM needed.
      const deps = [
        `    implementation("androidx.glance:glance-appwidget:${GLANCE_VERSION}")`,
        `    implementation("androidx.glance:glance-material3:${GLANCE_VERSION}")`,
      ].join("\n");
      src = src.replace(/dependencies\s*\{/, (m) => `${m}\n${deps}`);
    }

    if (!/compose\s+true/.test(src)) {
      src = src.replace(
        /android\s*\{/,
        (m) => `${m}\n    buildFeatures {\n        compose true\n    }`,
      );
    }

    config.modResults.contents = src;
    return config;
  });

// Expo's manifest types don't model android:label or <meta-data> on
// <receiver>, though the XML writer accepts both.
type ManifestReceiver = NonNullable<
  AndroidConfig.Manifest.ManifestApplication["receiver"]
>[number];
type LabeledManifestReceiver = ManifestReceiver & {
  $: ManifestReceiver["$"] & { "android:label"?: string };
  "meta-data"?: AndroidConfig.Manifest.ManifestMetaData[];
};

const withWidgetManifest: ConfigPlugin = (config) =>
  withAndroidManifest(config, (config) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(
      config.modResults,
    );

    app.receiver = app.receiver ?? [];
    const receiverName = `.${WIDGET_SUBDIR}.EvccLoadpointWidgetReceiver`;
    if (!app.receiver.some((r) => r.$["android:name"] === receiverName)) {
      const receiver: LabeledManifestReceiver = {
        $: {
          "android:name": receiverName,
          "android:exported": "false",
          "android:label": "@string/widget_loadpoint_name",
        },
        "intent-filter": [
          {
            action: [
              {
                $: {
                  "android:name": "android.appwidget.action.APPWIDGET_UPDATE",
                },
              },
            ],
          },
        ],
        "meta-data": [
          {
            $: {
              "android:name": "android.appwidget.provider",
              "android:resource": "@xml/loadpoint_widget_info",
            },
          },
        ],
      };
      app.receiver.push(receiver);
    }

    // widget placement configuration Activity (server, then loadpoint picker)
    app.activity = app.activity ?? [];
    const activityName = `.${WIDGET_SUBDIR}.LoadpointWidgetConfigActivity`;
    if (!app.activity.some((a) => a.$["android:name"] === activityName)) {
      app.activity.push({
        $: { "android:name": activityName, "android:exported": "true" },
        "intent-filter": [
          {
            action: [
              {
                $: {
                  "android:name":
                    "android.appwidget.action.APPWIDGET_CONFIGURE",
                },
              },
            ],
          },
        ],
      });
    }
    return config;
  });

// 2x2 square by default (like iOS systemSmall), horizontally resizable to a
// wide variant with the mode selector (systemMedium). LoadpointWidget.kt
// switches layout at its SizeMode.Responsive breakpoints (110 / 250dp wide).
const widgetInfoXml = `<?xml version="1.0" encoding="utf-8"?>
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:minWidth="110dp"
    android:minHeight="110dp"
    android:minResizeWidth="110dp"
    android:minResizeHeight="110dp"
    android:targetCellWidth="2"
    android:targetCellHeight="2"
    android:updatePeriodMillis="1800000"
    android:resizeMode="horizontal"
    android:widgetCategory="home_screen"
    android:configure="${PACKAGE}.${WIDGET_SUBDIR}.LoadpointWidgetConfigActivity"
    android:previewImage="@drawable/widget_preview_loadpoint"
    android:previewLayout="@layout/loadpoint_widget_preview" />
`;

// Material "refresh" glyph, tinted at runtime via Glance's ColorFilter.tint().
const reloadIconVector = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp" android:height="24dp"
    android:viewportWidth="24" android:viewportHeight="24">
    <path android:fillColor="#FF000000"
        android:pathData="M17.65,6.35C16.2,4.9 14.21,4 12,4c-4.42,0 -7.99,3.58 -7.99,8s3.57,8 7.99,8c3.73,0 6.84,-2.55 7.73,-6h-2.08c-0.82,2.33 -3.04,4 -5.65,4 -3.31,0 -6,-2.69 -6,-6s2.69,-6 6,-6c1.66,0 3.14,0.69 4.22,1.78L13,11h7V4l-2.35,2.35z" />
</vector>
`;

// Widget picker preview image: title / status / metric / power lines.
const loadpointPreviewImageVector = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="140dp" android:height="140dp"
    android:viewportWidth="140" android:viewportHeight="140">
    <path android:fillColor="#1B1B1B" android:pathData="M0,0h140v140h-140z" />
    <path android:fillColor="#FFFFFF" android:pathData="M16,18h70v12h-70z" />
    <path android:fillColor="#0FDE41" android:pathData="M16,38h50v8h-50z" />
    <path android:fillColor="#FFFFFF" android:pathData="M16,64h60v24h-60z" />
    <path android:fillColor="#333333" android:pathData="M16,96h108v6h-108z" />
    <path android:fillColor="#0FDE41" android:pathData="M16,96h60v6h-60z" />
    <path android:fillColor="#FFFFFF" android:pathData="M16,112h40v12h-40z" />
    <path android:fillColor="#B3FFFFFF" android:pathData="M94,114h30v9h-30z" />
</vector>
`;

// Static preview layout for the widget picker (Glance content only renders once placed).
const loadpointPreviewXml = `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="#1B1B1B"
    android:padding="16dp">
    <LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content"
        android:orientation="horizontal" android:gravity="center_vertical">
        <TextView android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content"
            android:text="@string/widget_loadpoint_name" android:textColor="#FFFFFF" android:textSize="14sp" android:textStyle="bold" />
        <ImageView android:layout_width="15dp" android:layout_height="15dp"
            android:src="@drawable/ic_reload" android:tint="#B3FFFFFF" />
    </LinearLayout>
    <LinearLayout android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:orientation="horizontal" android:gravity="center_vertical" android:paddingTop="3dp">
        <ImageView android:layout_width="7dp" android:layout_height="7dp" android:background="@drawable/widget_preview_dot" />
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:paddingStart="5dp"
            android:text="@string/widget_lpstatus_charging" android:textColor="#0FDE41" android:textSize="11sp" />
    </LinearLayout>
    <FrameLayout android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" />
    <LinearLayout android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:orientation="horizontal" android:gravity="bottom">
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
            android:text="62" android:textColor="#FFFFFF" android:textSize="30sp" android:textStyle="bold" />
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:paddingBottom="4dp"
            android:text=" %" android:textColor="#B3FFFFFF" android:textSize="14sp" android:textStyle="bold" />
    </LinearLayout>
    <FrameLayout android:layout_width="match_parent" android:layout_height="6dp" android:layout_marginTop="6dp">
        <ImageView android:layout_width="match_parent" android:layout_height="match_parent" android:background="@drawable/widget_preview_track" />
        <LinearLayout android:layout_width="match_parent" android:layout_height="match_parent" android:orientation="horizontal">
            <ImageView android:layout_width="0dp" android:layout_weight="62" android:layout_height="match_parent" android:background="@drawable/widget_preview_fill" />
            <ImageView android:layout_width="0dp" android:layout_weight="38" android:layout_height="match_parent" />
        </LinearLayout>
    </FrameLayout>
    <FrameLayout android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" />
    <LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content"
        android:orientation="horizontal" android:gravity="bottom">
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
            android:text="7.4" android:textColor="#FFFFFF" android:textSize="15sp" android:textStyle="bold" />
        <TextView android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content" android:paddingBottom="1dp"
            android:text=" kW" android:textColor="#B3FFFFFF" android:textSize="12sp" android:textStyle="bold" />
        <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:paddingBottom="1dp"
            android:text="@string/widget_mode_smart" android:textColor="#B3FFFFFF" android:textSize="12sp" />
    </LinearLayout>
</LinearLayout>
`;

const roundedShape = (
  color: string,
  radius: string,
) => `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="${color}" />
    <corners android:radius="${radius}" />
</shape>
`;

// key → locale → value
type Translations = Record<string, Record<string, string>>;

function loadTranslations(projectRoot: string): {
  translations: Translations;
  locales: string[];
} {
  const catalog = JSON.parse(
    fs.readFileSync(path.join(projectRoot, XCSTRINGS), "utf8"),
  ) as {
    sourceLanguage: string;
    strings: Record<
      string,
      { localizations: Record<string, { stringUnit: { value: string } }> }
    >;
  };
  const translations: Translations = {};
  for (const [key, entry] of Object.entries(catalog.strings)) {
    translations[key] = Object.fromEntries(
      Object.entries(entry.localizations).map(([locale, l]) => [
        locale,
        l.stringUnit.value,
      ]),
    );
  }

  const i18nDir = path.join(projectRoot, APP_I18N);
  const locales = fs
    .readdirSync(i18nDir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => path.basename(f, ".json"))
    .sort();
  const en = JSON.parse(fs.readFileSync(path.join(i18nDir, "en.json"), "utf8"));
  const androidOnlyKeys = Object.keys(en.widget?.androidConfig ?? {}).map(
    (k) => `${ANDROID_ONLY_PREFIX}${k}`,
  );
  const lookup = (json: Record<string, unknown>, key: string) =>
    key
      .split(".")
      .reduce<unknown>(
        (o, k) => (o as Record<string, unknown> | undefined)?.[k],
        json,
      );
  for (const key of androidOnlyKeys) translations[key] = {};
  for (const locale of locales) {
    const json = JSON.parse(
      fs.readFileSync(path.join(i18nDir, `${locale}.json`), "utf8"),
    );
    for (const key of androidOnlyKeys) {
      const value = lookup(json, key) ?? lookup(en, key);
      if (typeof value === "string") translations[key][locale] = value;
    }
  }
  return { translations, locales };
}

// Escape XML entities plus what Android's resource parser treats specially.
function escapeAndroid(value: string): string {
  let s = value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"');
  if (/^[@?]/.test(s)) s = `\\${s}`;
  return s;
}

// "widget.mode.off" → <string name="widget_mode_off">; "nb-NO" → values-b+nb+NO
function writeStrings(
  resDir: string,
  translations: Translations,
  locales: string[],
  sourceLang = "en",
) {
  const keys = Object.keys(translations).sort();
  for (const locale of locales) {
    const dir = path.join(
      resDir,
      locale === sourceLang
        ? "values"
        : `values-b+${locale.split("-").join("+")}`,
    );
    fs.mkdirSync(dir, { recursive: true });
    const entries = keys
      .map((key) => {
        const value =
          translations[key][locale] ?? translations[key][sourceLang];
        return `    <string name="${key.replace(/\./g, "_")}">${escapeAndroid(value)}</string>`;
      })
      .join("\n");
    const file = path.join(dir, "strings.xml");
    if (fs.existsSync(file)) {
      // prebuild already wrote app_name etc. into values/strings.xml — merge
      const existing = fs.readFileSync(file, "utf8");
      fs.writeFileSync(
        file,
        existing.replace("</resources>", `${entries}\n</resources>`),
      );
    } else {
      fs.writeFileSync(
        file,
        `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n${entries}\n</resources>\n`,
      );
    }
  }
}

const withWidgetFiles: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "android",
    (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const main = path.join(
        config.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
      );
      const res = path.join(main, "res");

      const dest = path.join(
        main,
        "java",
        ...PACKAGE.split("."),
        WIDGET_SUBDIR,
      );
      fs.mkdirSync(dest, { recursive: true });
      const srcDir = path.join(projectRoot, KOTLIN_SRC);
      for (const f of fs.readdirSync(srcDir).filter((f) => f.endsWith(".kt"))) {
        fs.copyFileSync(path.join(srcDir, f), path.join(dest, f));
      }

      const files: Record<string, string> = {
        "xml/loadpoint_widget_info.xml": widgetInfoXml,
        "layout/loadpoint_widget_preview.xml": loadpointPreviewXml,
        "drawable/widget_preview_loadpoint.xml": loadpointPreviewImageVector,
        "drawable/ic_reload.xml": reloadIconVector,
        "drawable/widget_preview_dot.xml": roundedShape("#0FDE41", "4dp"),
        "drawable/widget_preview_track.xml": roundedShape("#33FFFFFF", "3dp"),
        "drawable/widget_preview_fill.xml": roundedShape("#0FDE41", "3dp"),
      };
      for (const [rel, content] of Object.entries(files)) {
        const target = path.join(res, rel);
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.writeFileSync(target, content);
      }

      const { translations, locales } = loadTranslations(projectRoot);
      writeStrings(res, translations, locales);

      return config;
    },
  ]);

const withAndroidWidget: ConfigPlugin = (config) => {
  config = withComposeClasspath(config);
  config = withGlanceGradle(config);
  config = withWidgetManifest(config);
  config = withWidgetFiles(config);
  return config;
};

export default withAndroidWidget;
